apiVersion: v1
kind: Pod
metadata:
  name: paragraphanalytics
  labels:
    app: paragraphanalytics
spec:
  containers:
    - name: paragraphanalytics
      image: svaddaram/paragraphanalytics:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 65000
  imagePullSecrets: 
    - name: regcred
