apiVersion: v1
kind: Pod
metadata:
  name: paragraphanalytics
  labels:
    app: web
spec:
  containers:
    - name: uses-private-image
      image: svaddaram/paragraphanalytics:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 65000
  imagePullSecrets: 
    - name: regcred
