apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    run: my-service
spec:
  type: NodePort
  ports:
  - port: 65000
    protocol: TCP
    targetPort: 65000
  selector:
    run: paragraphanalytics
  externalIPs:
    - 80.11.12.10
 